import BlogList from "../../../components/HOME/blog/blog"
import DonateHeader from "../../../components/DONATE/donate-header/donate-header"
import DonateIntroVideo from "../../../components/DONATE/IntroVideo/introVideo"
import Causes from "../../../components/DONATE/causes/causes"
import { groq } from "next-sanity"
import { client } from "../../../lib/sanity.client"

import "../../../styles/about.scss"
import "../../../styles/globals.css"

const query = groq`*[_type == 'cause']{
  ...
}`;

export const metadata = {
  title: 'Donate Now || Donate to the Treasure Trees Cause',
  description: 'Generated by create next app',
}

export default async function Page() {
  const cause = await client.fetch(query);
  return (
    <>
        <DonateHeader causes={cause}/>
        <DonateIntroVideo/>
        <Causes causes={cause}/>
    </>
  )
}
